version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: femfund-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: femfund
    networks:
      - femfund-network

  # Backend service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: femfund-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/femfund?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - femfund-network

  # Frontend service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: femfund-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5000/api
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - femfund-network

networks:
  femfund-network:
    driver: bridge

volumes:
  mongo-data: